[package]
name = "killswitch_std"
version = "0.2.0"
edition = "2021"

[dependencies]

[dev-dependencies]
tokio = { version = "1.42.0", features = ["macros", "time"] }
tokio-test = "0.4.4"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
